# Vetores, matrizes e Tensores com Pytorch

## 1. Introdução


Veremos que as operações das redes neurais artificiais podem ser convenientemente descritas na forma de vetores e matrizes (arrays) de várias dimensões. Na área de IA, especialmente na comunidade de computação, as matrizes de dimensão maior que 2 são geralmente chamadas tensores. Existe alguma polêmica nisso, já que tensores são objetos de física-matemática que generalizam a ideia de vetores e matrizes, que só fazem sentido a partir de um sistema de coordenadas de referência, e que devem satisfazer certas propriedades de transformação. 

Este caderno é uma adaptação de cadernos do livro "Dive into Deep Learning". Modificou-se ligeiramente alguns exemplos e alguns comentários foram incluídos para quem não é tão familiarizado com Python e Pytorch. 

## 2. Arrays de várias dimensões

### 2.1. Criação e Manipulação

In [1]:
import torch

Primeiro, vejamos a criação com `arange(N)`. Com parâmetros default, a função cria uma sequência de valores de 0 a N-1, em passos de 1. 

In [3]:
x = torch.arange(13, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

Observe que, internamente, Python trata o vetor como uma lista de números. Python é todo orientado para tratar com listas, e elas são definidas entre colchetes. 

Agora vejamos a criação de um array com a função `zeros` . Ela cria um array de zeros com o tamanho especificado. 

In [4]:
x=torch.zeros((2,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Observe os parênteses duplos. A função aceita o tamanho do array a ser criado como uma "tupla". Tupla é uma lista imutável (estática), não pode ser manipulada depois de criada. Veja também que a matriz (bi-dimensional) é descrita como uma lista de listas.

É possível também confirmar as dimensões de `x` por meio do seu atributo `shape`. Trata-se de uma matriz 2x3 (ou, se preferir uma lista de 2 vetores de 3 elementos).

In [7]:
x.shape

torch.Size([2, 3])

Como você deve ter imaginado, `ones` cria arrays preenchidos com 1s. 

In [6]:
torch.ones((2,3,2))

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

Arrays de dimensão 3 (ou tensores, lembre-se da polêmica citada antes...) são obviamente listas de listas de... listas. Finalmente, podemos (e frequentemente queremos) gerar arrays com valores aleatórios. Isso pode ser feito, por exemplo, com a função a seguir que cria um array de valores amostrados a partir de uma distribuição normal (gaussiana) com média 0 e desvio-padrão 1.

In [9]:
torch.randn((2,2))

tensor([[ 0.0691, -0.8332],
        [-0.1254,  1.0966]])

A função `tensor` pode ser usada para especificar os elementos do array um a um.

In [10]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### 2.2. Indexação, fatiamento e reforma

O sistema de indexação para listas em Python (e consequentemente para arrays) causa alguma estranheza a princípio. O primeiro elemento é o 0. Índices negativos podem ser usados para acessar valores a partir do fim da lista.

In [11]:
x=torch.tensor([1,2,3,4,5])
x[0],x[4],x[-1],x[-2]

(tensor(1), tensor(5), tensor(5), tensor(4))

As faixas `a:b` como índice selecionam os elementos de `a` até o **antecessor** de `b`. Se `a` for omitido, entende-se "do começo", se `b` for omitido, "até o final". 

In [14]:
x[0:3], x[-3:-1],x[0:-1],x[:2],x[2:]

(tensor([1, 2, 3]),
 tensor([3, 4]),
 tensor([1, 2, 3, 4]),
 tensor([1, 2]),
 tensor([3, 4, 5]))

In [15]:
x = torch.arange(9)
X = x.reshape(3,3)
x, X

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

Acima usamos a função `reshape` do objeto `x` para transformar o vetor de 9 elementos em uma matriz 3x3. Se omitirmos uma das dimensões, selecionamos todo o elemento. Por exemplo, se o índice tem uma dimensão apenas, entende-se toda a linha:

In [16]:
X[-1],X[:2]

(tensor([6, 7, 8]),
 tensor([[0, 1, 2],
         [3, 4, 5]]))

Naturalmente, podemos modificar o valor de um elemento em um array:

In [17]:
X[1,2] = -4
X

tensor([[ 0,  1,  2],
        [ 3,  4, -4],
        [ 6,  7,  8]])

### 2.3. Operações elemento a elemento

As operações como +, *, / e ** são feitas elemento a elemento. 

In [18]:
x=torch.tensor([[1,2],[3,4]])
y=torch.tensor([[0,1],[2,3]])
x,y,x+y, x*y, y/x, x**y

(tensor([[1, 2],
         [3, 4]]),
 tensor([[0, 1],
         [2, 3]]),
 tensor([[1, 3],
         [5, 7]]),
 tensor([[ 0,  2],
         [ 6, 12]]),
 tensor([[0.0000, 0.5000],
         [0.6667, 0.7500]]),
 tensor([[ 1,  2],
         [ 9, 64]]))

Notar que os tipos são implícitos. Veja como o resultado da divisão é um float64 e os demais inteiros. 

Outra operação útil é a de concatenação. O atributo `dim` indica qual dimensão será concatenada `dim=0` 
significa concatene no sentido das linhas, `dim=1` concatene no sentido das colunas, etc. 

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X,Y,torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Uma expressão lógica envolvendo arrays é aplicada elemento a elemento. O resultado é um novo array onde um elemento vale "true" quando a condição é satisfeita 
e "false" quando não é. 

In [20]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

# 3. Arquivos

Frequentemente, os dados para treinar um modelo estão localizados em longos arquivos CSV (valores separados por vírgula). Nesta seção vamos seguir um exemplo do d2l: criar um pequeno arquivo de exemplo, lê-lo e manipulá-lo. 

In [21]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

`os` é o módulo que contém as funções de interface com o sistema operacional. A função `makedirs` com os parâmetros acima cria um diretório chamado `data` acima do diretório atual, a menos que já exista. `data_file` é o ponteiro para o novo arquivo `House_tiny.csv` a ser criado. O `write` escreve o string determinado neste arquivo. As 3 aspas simples indicam que o string se estende por mais de uma linha. 

Agora, importamos o módulo pandas, que têm funções de manipulação de dados, e lemos o arquivo. 

In [22]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)


   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


A função `pd.read_csv` devolve um "Dataframe", uma estrutura bidimensional com diferentes tipos de dados (note como a tabela tem textos e números). O "NA" que incluímos na Tabela é uma indicação de um dado faltante, algo comum em grandes bases de dados do mundo real. Esta Tabela (se tivesse milhares de registros e não 4...) poderia ser uma base de dados de preços de casas a partir do número de quartos e tipo de telhado, para um problema de regressão (estimar o preço de uma nova casa que não está na base). Neste caso, as entradas seriam os valores das duas primeiras colunas, e o alvo (saída) a última. Vamos separar os dados em entradas e saídas. 

In [23]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs)
print(targets)

   NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      NaN
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


O atributo `iloc` é usado para acessar pontos específicos do dataframe, com as mesmas regras de indexação que vimos anteriormente. 

Agora vamos tratar da questão do NA. Se o dado faltante é uma categoria, geralmente a solução é criar uma nova categoria "NA". Como todos os tipos de telhados que existem são "Slate" (Ardósia), vão passar a existir duas categorias de telhado: Slate ou NA. 

In [24]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


A função ``pd.get_dummies`` transforma as colunas de categoria em expressões lógicas ("True" se a categoria do nome da coluna está presente, "False" se não está). Com a opção ``dummy_na=True``, é criada uma coluna para os casos em que a informação de categoria é inexistente. 

Para o caso de valores numéricos faltantes, uma solução comum é atribuir a média dos valores existentes. 

In [25]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


O método `fillna` aplicado a qualquer Dataframe substitui os valores NA com os valores dados. No caso, a média da coluna, acessada pelo método `mean`

Os dados estão separados em uma matriz de entrada e um vetor correspondente de saída, as categorias estão expressas como variáveis lógicas, e não há valores faltantes. Mas `inputs` e `targets` ainda são "dataframes". Para transformá-las em objeto tensor, usamos a função `torch.tensor` e o método `to_numpy` aplicado ao dataframe. 

In [26]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
print(X), print(y)

tensor([[3., 0., 1.],
        [2., 0., 1.],
        [4., 1., 0.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


(None, None)